{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_allure.py:9: AssertionError"}, "description": "this test fails", "start": 1700331011297, "stop": 1700331011297, "uuid": "8c762c89-91d7-4fd7-ac4f-c1f1be52889c", "historyId": "831c39b42e655530a19927dc1ea2cf01", "testCaseId": "831c39b42e655530a19927dc1ea2cf01", "fullName": "demo.test_allure#test_failure", "labels": [{"name": "parentSuite", "value": "demo"}, {"name": "suite", "value": "test_allure"}, {"name": "host", "value": "LAPTOP-J67UEDPK"}, {"name": "thread", "value": "28452-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "demo.test_allure"}]}